using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.SceneManagement;

public class PauseMenu3 : MonoBehaviour
{
    public GameObject pauseMenu;
    public static bool isPaused;

    
    public PlayerDash playerController;

    void Start()
    {
        pauseMenu.SetActive(false);
        Time.timeScale = 1f;

    }

    void Update()
    {
        if (Input.GetKeyUp(KeyCode.Escape))
        {
            if (isPaused)
            {
                ResumeGame();
            }
            else
            {
                PauseGame();
            }
        }
    }

    public void PauseGame()
    {
        // Disable player control
        playerController.enabled = false;

        pauseMenu.SetActive(true);
        Time.timeScale = 0f;
        isPaused = true;
    }

    public void ResumeGame()
    {
        // Enable player control
        playerController.enabled = true;

        pauseMenu.SetActive(false);
        Time.timeScale = 1f;
        isPaused = false;
    }

    public void RestartGame()
    {
        SceneManager.LoadScene(SceneManager.GetActiveScene().name);
        ResumeGame();
    }

    public void BackToMenu()
    {
        SceneManager.LoadScene(0);
    }
}
